modules/backend/controllers/DefaultController.php
<?php

namespace app\modules\backend\controllers;

use app\helpers\DateAndTime;
use app\modules\base\models\InstallForm;
use app\modules\base\models\LoginForm;
use app\modules\base\models\PasswordResetForm;
use app\modules\base\models\PasswordResetRequestForm;
use app\modules\base\models\RegisterForm;
use app\modules\base\models\Setting;
use app\modules\base\models\User;
use app\modules\base\models\UserAuthConnection;
use yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;

class DefaultController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['install', 'error'],
                    ],
                    [
                        'allow' => true,
                        'actions' => [
                            'login',
                            'auth-connection-login',
                            'register',
                            'register-ajax-validation',
                            'password-reset-request',
                            'password-reset'
                        ],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'auth-connection-login' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'authConnectionLoginCallback'],
            ],

        ];
    }

    public function actionInstall()
    {
        $this->layout = 'minimal';

        /* If user table exists and any users exist, install is complete and should not be allowed to continue */
        $userTableSchema = Yii::$app->db->schema->getTableSchema('{{%user}}');
        if ($userTableSchema != null && User::find()->count() > 0) {
            return $this->redirect(['/admin']);
        }

        $model = new InstallForm();
        if ($model->load(Yii::$app->request->post()) && $model->updateSettings()) {
            /* So that when the user logs in the call to goBack() goes to the admin */
            Yii::$app->user->returnUrl = '/admin';
            return $this->redirect(['/admin/default/login']);
        } else {
            /* Set flash message if model failed validation (meaning the install did not complete) */
            if ($model->hasErrors()) {
                Yii::$app->getSession()->addFlash('warning', 'Install failed, please review data entered in Installation Wizard.');
            }
            return $this->render('install', [
                'model' => $model,
            ]);
        }
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        /* If user is logged in go back to previous page. Authenticated users do not have access to login page. */
        if (!Yii::$app->user->isGuest) {
            return $this->goBack();
        }

        $model = new LoginForm();

        /* If Ajax request, perform login checks and log in if everything checks out */
        if (Yii::$app->request->isAjax) {

            /* Response will be Json */
            Yii::$app->response->format = Response::FORMAT_JSON;

            /* Load the posted data and attempted login */
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                /* Return errors */
                $result['notify'] = implode('. ', $model->getFirstErrors());
                $result['notifyType'] = 'warning';
                /*
                 * This is used by the action-login.js to determine if the user needs to be shown the two-factor code
                 * or not. The two-factor code will not be required or validated until username and password are
                 * valid so if the two-factor code has an error, that means it is either required and blank or invalid.
                 * There will only ever be two errors for two-factor code: A) it is blank and required, B) it is wrong.
                 * If it is blank and required, that may simply be because it has not been shown yet such as when the
                 * user first enters a valid username and password. In this case, the JS can show the two-factor code
                 * and not display the error. If it is blank again, the JS can determine that it is already shown and
                 * the user just did not enter a value in which case the error can be shown. The next option is that it
                 * is invalid. This can only happen after the two-factor code has been shown and populated. In this
                 * case, the JS will simply clear the field and display an error.
                 */
                $result['twoFactorCodeError'] = $model->hasErrors('two_factor_code');
            }

            return $result;

        } else {
            $this->layout = 'minimal';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $client \yii\authclient\ClientInterface
     */
    public function authConnectionLoginCallback($client)
    {
        $attributes = $client->getUserAttributes();

        // Cloud ID for User Cloud Account
        $authClientId = $client->getId() . '-' . $attributes['id'];

        // If User Cloud Account exists, login
        if ($userAuthClient = UserAuthConnection::findOne(['id' => $authClientId])) {
            $user = $userAuthClient->user;
            /* Send loginNotification email */
            $user->sendLoginNotificationEmail();
            // Login User
            $user_session_duration = Setting::getSetting('user_session_duration');
            Yii::$app->user->login($user, $user_session_duration);
        } else {
            Yii::$app->getSession()->addFlash('warning',
                'The ' . $client->getTitle() . ' account you have selected is not associated with any user on this site. Login with your username and password to connect your user account to this ' . $client->getTitle() . ' account.');
        }
    }

    /**
     * Logs out a user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        /* Remove long-lasting admin_user_exists cookie. Only removed by manual logging out (or one year passes) */
        Yii::$app->response->cookies->remove('admin_user_exists');

        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Registers an invited user.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionRegister($token)
    {
        $this->layout = 'minimal';

        try {
            $model = new RegisterForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->register()) {
            Yii::$app->session->setFlash('success', 'Registration successful. Please login.');
            // Set the return url as the main admin page
            Yii::$app->user->returnUrl = ['/admin'];

            return $this->redirect(['/admin/default/login']);
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * Ajax validation for the register form
     *
     * @param string $token
     * @return mixed
     */
    public function actionRegisterAjaxValidation($token)
    {
        $model = new RegisterForm($token);

        $model->load(Yii::$app->request->post());

        Yii::$app->response->format = Response::FORMAT_JSON;

        return ActiveForm::validate($model, ['username']);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionPasswordResetRequest()
    {
        $this->layout = 'minimal';

        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->redirect(['/admin/default/login']);
            } else {
                Yii::$app->session->setFlash('warning', 'Error sending password reset email.');
            }
        }

        return $this->render('passwordResetRequest', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionPasswordReset($token)
    {
        $this->layout = 'minimal';

        try {
            $model = new PasswordResetForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {

modules/backend/views/default/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use app\modules\backend\widgets\Panel;
use yii\helpers\Html;

$this->title = $name;
$this->params['breadcrumbs'][] = 'Error';

if (Yii::$app->user->isGuest) {
    /** @noinspection PhpUndefinedFieldInspection */
    $this->context->layout = 'minimal';
}
?>
<div class="site-error content-wrapper content-wrapper_minimal">

    <?php Panel::begin(['title' => 'Error: ' . Html::encode($this->title)]); ?>

    <p><?= nl2br(Html::encode($message)) ?></p>

    <?php Panel::end(); ?>

</div>

modules/backend/views/default/index.php
<?php

use app\modules\backend\widgets\Panel;

$this->title = 'Admin';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="post-index content-wrapper">

    <?php Panel::begin(['title' => $this->title]); ?>

    Body content

    <?php Panel::end(); ?>

</div>

modules/backend/views/default/install.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \app\modules\base\models\InstallForm */

use app\modules\backend\widgets\Panel;
use app\modules\base\models\Setting;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Install';

/* Active page, by default, is the first page, introducing the installation wizard */
$activePage = 0;
/* If the model has errors, the active page will be the first page with errors */
if ($model->hasErrors()) {
    $errors = $model->getFirstErrors();
    /* Page/step 1 */
    if (array_key_exists('blogTitle', $errors)
        || array_key_exists('blogTagline', $errors)
    ) {
        $activePage = 1;
    } elseif (array_key_exists('firstName', $errors)
        || array_key_exists('lastName', $errors)
        || array_key_exists('emailAddress', $errors)
    ) {
        $activePage = 2;
    } elseif (array_key_exists('username', $errors)
        || array_key_exists('password', $errors)
    ) {
        $activePage = 3;
    } elseif (array_key_exists('supportEmailAddress', $errors)
    ) {
        $activePage = 4;
    }
}
?>

    <div class="site-install content-wrapper content-wrapper_minimal">

        <?php Panel::begin(['title' => $this->title]); ?>

        <div class="install-form">

            <?php $form = ActiveForm::begin([
                'id' => 'install-form',
                'enableClientValidation' => false,
            ]); ?>

            <div class="wizard-page-container">

                <div class="wizard-page page-first <?= ($activePage == 0) ? 'page-active' : null ?>">

                    <h2>Installation Wizard</h2>

                    <p>The following pages will walk you through entering blog and user information to complete the
                        installation. All fields are required and all of the data entered here can be changed by
                        navigating to the <em>Settings</em> page once logged in.</p>

                    <p>Click <strong>Next</strong> below to get started.</p>

                </div>

                <div class="wizard-page <?= ($activePage == 1) ? 'page-active' : null ?>">

                    <h2>Step 1 of 4 - Blog basics</h2>

                    <p>To get started, give your blog a title and catchy tagline.</p>

                    <?= $form->field($model, 'blogTitle')
                        ->textInput() ?>

                    <?= $form->field($model, 'blogTagline')
                        ->textarea(['rows' => 2]) ?>

                </div>

                <div class="wizard-page <?= ($activePage == 2) ? 'page-active' : null ?>">

                    <h2>Step 2 of 4 - User name and email</h2>

                    <p>Next, some basic information about yourself</p>

                    <div class="clearfix">
                        <div class="half-width half-width-left">
                            <?= $form->field($model, 'firstName')
                                ->textInput() ?>
                        </div>
                        <div class="half-width half-width-right">
                            <?= $form->field($model, 'lastName')
                                ->textInput() ?>
                        </div>
                    </div>

                    <?= $form->field($model, 'emailAddress')
                        ->textInput() ?>

                </div>

                <div class="wizard-page <?= ($activePage == 3) ? 'page-active' : null ?>">

                    <h2>Step 3 of 4 - User credentials</h2>

                    <p>Login credentials so you can log in.</p>

                    <?= $form->field($model, 'username')
                        ->textInput() ?>

                    <?= $form->field($model, 'password')
                        ->passwordInput() ?>

                </div>

                <div class="wizard-page page-last <?= ($activePage == 4) ? 'page-active' : null ?>">

                    <h2>Step 4 of 4 - Blog setup</h2>

                    <p>Finally, just a couple required administrative settings.</p>

                    <?= $form->field($model, 'supportEmailAddress')
                        ->textInput() ?>

                    <?= $form->field($model, 'timeZone')
                        ->dropDownList(Setting::getTimeZones()) ?>

                </div>
            </div>

            <div class="wizard-controls clearfix">
                <?= Html::button('Previous', ['class' => 'btn btn-default pull-left page-prev hidden']) ?>

                <?= Html::button('Next', ['class' => 'btn btn-default pull-right page-next']) ?>
                <?= Html::submitButton('Install', ['class' => 'btn btn-scheme pull-right hidden btn-submit']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div> <!-- .install-form -->

        <?php Panel::end(); ?>

    </div> <!-- .site-install -->

<?php
$script = <<< JS

    /* Since the active page may not be the first page, perform updateButtons on page load */
    updateButtons();

    /* On click of next button, show next page */
    $("button.page-next").click(function() {
        $(".wizard-page.page-active").removeClass("page-active").next().addClass("page-active");
        updateButtons();
    });
    /* On click of previous button, show previous page */
    $("button.page-prev").click(function() {
        $(".wizard-page.page-active").removeClass("page-active").prev().addClass("page-active");
        updateButtons();
    });

    function updateButtons() {
        /* Send focus to the first visible field */
        $('#install-form :input:visible:enabled:first').focus();
        /* Hide previous button when on first page */
        $("button.page-prev").toggleClass("hidden", $(".wizard-page.page-active").hasClass("page-first"));
        /* Hide next button when on last page */
        $("button.page-next").toggleClass("hidden", $(".wizard-page.page-active").hasClass("page-last"));
        /* Show install button when on last page */
        $("button.btn-submit").toggleClass("hidden", !$(".wizard-page.page-active").hasClass("page-last"));
    }

    /* Continue from page to page on press of enter key */
    $(document).on('keypress',  function(e) {
        /* If enter key was pressed and target was anything other than "previous" button ... */
        if(e.key === "Enter" && !$(e.target).hasClass('page-prev')) {
            /* ... as long as this is not the last page, click the next page button and do not submit the form */
            if (!$(".wizard-page.page-active").hasClass("page-last")) {
                /* Click the "next" button */
                $("button.page-next").click();
                /* Prevent the form from submitting */
                e.preventDefault();
            }
        }
    });

JS;
$this->registerJs($script, $this::POS_READY);

modules/backend/views/default/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \app\modules\base\models\LoginForm */

use app\modules\backend\widgets\Panel;
use app\modules\backend\widgets\PasswordInput;
use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* Register the JavaScript necessary for publishing and unpublishing posts */
$this->registerJsFile('/backend/js/default/action-login.js', ['depends' => '\app\assets\AdminAsset']);

$this->title = 'Login';
?>
<div class="site-login content-wrapper content-wrapper_minimal">

    <?php Panel::begin(['title' => $this->title]); ?>

    <div class="login-form">

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'enableClientValidation' => false,
        ]); ?>

        <div class="wizard-page-container">

            <div class="wizard-page page-active">

                <?= $form->field($model, 'username')
                    ->textInput(['autofocus' => true])->label('Username or email address') ?>

                <?= $form->field($model, 'password')
                    ->widget(PasswordInput::className(),
                        ['options' => ['class' => 'form-control']]) ?>

            </div>

            <div class="wizard-page page-two-factor">

                <?= $form->field($model, 'two_factor_code')
                    ->widget(PasswordInput::className(), ['options' => ['class' => 'form-control']])
                    ->label('Two-factor authentication code') ?>

            </div>
        </div>

        <?= Html::submitButton('Login', ['class' => 'btn btn-scheme btn-block btn-login', 'name' => 'login-button']) ?>

        <div class="forgot-password">
            <?= Html::a('Forgot password?', ['default/password-reset-request']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

    <?php Panel::end(); ?>

    <?php
    /* Only going to display second block if auth clients are set */
    if (array_key_exists('authClientCollection', Yii::$app->components)
        && count(Yii::$app->components['authClientCollection']['clients']) > 0
    ) {

        echo '<div class="auth-clients-wrapper">';

        echo '<p>Or, log in with one of the following services</p>';

        /* Begin AuthChoice widget */
        $authAuthChoice = AuthChoice::begin([
            'baseAuthUrl' => ['/admin/default/auth-connection-login'],
            'options' => ['class' => 'auth-clients'],
        ]);

        /* Loop through each configured AuthChoice Client */
        foreach ($authAuthChoice->getClients() as $client) {
            echo $authAuthChoice->clientLink($client);
        }

        /* End AuthChoice widget */
        AuthChoice::end();

        echo '</div>';
    }
    ?>

</div>

modules/backend/views/default/passwordReset.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \app\modules\base\models\PasswordResetForm */

use app\modules\backend\widgets\Panel;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-password-reset content-wrapper content-wrapper_minimal">

    <?php Panel::begin(['title' => $this->title]); ?>

    <p>Please enter your new password.</p>

    <div class="reset-password-form">

        <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

        <?= $form->field($model, 'password')->passwordInput(['autofocus' => true])->label('New password') ?>

        <div class="form-group right-align">
            <?= Html::submitButton('Save', ['class' => 'btn btn-scheme']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

    <?php Panel::end(); ?>

</div>

modules/backend/views/default/passwordResetRequest.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \app\modules\base\models\PasswordResetRequestForm */

use app\modules\backend\widgets\Panel;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-password-reset-request content-wrapper content-wrapper_minimal">

    <?php Panel::begin(['title' => $this->title]); ?>

    <p>Please enter your email address. A link to reset your password will be sent there.</p>

    <div class="request-password-reset-form">

        <?php $form = ActiveForm::begin([
            'id' => 'request-password-reset-form',
            'enableClientValidation' => false,
        ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true])->label('Email address') ?>

        <div class="form-group right-align">
            <?= Html::a('Cancel', ['/admin/default/login'], ['class' => 'btn btn-default']) ?>
            <?= Html::submitButton('Send', ['class' => 'btn btn-scheme']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>

    <?php Panel::end(); ?>
</div>

modules/backend/views/default/register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \app\modules\base\models\RegisterForm */

use app\modules\backend\widgets\Panel;
use app\modules\backend\widgets\PasswordInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-register content-wrapper content-wrapper_minimal">

    <?php Panel::begin(['title' => $this->title]); ?>

    <div class="register-form">

        <p>Finish creating your account</p>

        <?php $form = ActiveForm::begin([
            'id' => 'register-form',
            'enableAjaxValidation' => true,
            'validationUrl' => ['register-ajax-validation', 'token' => $model->security_token],
            'action' => ['register', 'token' => $model->security_token],
        ]); ?>

        <?= $form->field($model, 'first_name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'last_name')->textInput() ?>

        <?= $form->field($model, 'username')->textInput() ?>

        <?= $form->field($model, 'password')->widget(PasswordInput::className()) ?>

        <div class="form-group right-align">
            <?= Html::submitButton('Register', ['class' => 'btn btn-scheme']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

    <?php Panel::end(); ?>

</div>