modules/backend/controllers/TagController.php
<?php

namespace app\modules\backend\controllers;

use app\modules\base\models\Tag;
use app\modules\backend\models\TagSearch;
use yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index',
                            'view',
                            'create',
                            'update',
                            'delete',
                            'ajax-create',
                            'ajax-validate',
                        ],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Tag models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tag model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = Tag::findModel($id);
        $postsDataProvider = new ActiveDataProvider([
            'query' => $model->primaryPosts(),
        ]);
        $pagesDataProvider = new ActiveDataProvider([
            'query' => $model->primaryPages(),
        ]);

        return $this->render('view', [
            'model' => $model,
            'posts' => $postsDataProvider,
            'pages' => $pagesDataProvider,
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws HttpException
     */
    public function actionCreate()
    {
        $model = new Tag();

        if (\Yii::$app->user->can('tagCreate')) {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new HttpException(403, 'You do not have permission to create tags.');
        }
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws HttpException
     */
    public function actionUpdate($id)
    {
        $model = Tag::findModel($id);

        if (\Yii::$app->user->can('tagUpdate', ['model' => $model])) {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new HttpException(403, 'You do not have permission to update this record.');
        }
    }

    /**
     * Deletes an existing Tag model (or models).
     * After delete, the browser will be redirected to the 'index' page.
     * @param string $ids
     * @return mixed
     */
    public function actionDelete($ids)
    {
        /* Split the list of comma-separated ids into an array */
        $ids = explode(',', $ids);

        /* Retrieve all models based on the primary keys */
        $models = Tag::findAll($ids);

        /*
         * Loop through each model, checking for:
         * 1) Permission to delete
         * 2) Whether or not the tag is in use
         * Permission must be granted and the tag must not be in use in order to allow deletion. If either
         * condition is not met, an error message is added.
         */
        $errorMessages = [];
        foreach ($models as $model) {
            /* Add error if permission to delete is denied */
            if (!\Yii::$app->user->can('tagDelete', ['model' => $model])) {
                $errorMessages[] = '<b>' . $model->name . '</b>, permission denied.';
            }
            /* Add error if tag is in use and thus cannot be deleted */
            if ($model->primary_posts_count != 0 || $model->primary_pages_count != 0) {
                $errorMessages[] = '<b>' . $model->name . '</b>, in use and cannot be deleted.';
            }
        }

        /*
         * If there were any errors, $errorMessages will contain values.
         * If there are values in the error message list, add a flash alert and do not delete. Else, continue with
         * deletion of each record.
         */
        if (count($errorMessages) > 0) {
            $message = 'Delete cancelled due to the following:<br>' . implode('<br>', $errorMessages);
            Yii::$app->getSession()->addFlash('warning', $message);
        } else {

            /* Start transaction so that if any deletion fails, entire transaction can be rolled back. */
            $transaction = Tag::getDb()->beginTransaction();
            try {

                /* Loop through each model and delete it. Failures throw exceptions that roll back the transaction. */
                foreach ($models as $model) {
                    $model->delete();
                }

                /* Since no exceptions were thrown during deletions, commit the transaction. */
                $transaction->commit();

                /* Add success flash alert. */
                $message = (count($models) == 1) ? 'Tag deleted.' : 'Tags deleted.';
                Yii::$app->getSession()->addFlash('success', $message);

            } /** @noinspection PhpUndefinedClassInspection */ catch(\Throwable $e) {
                /* If any exceptions where thrown during deletions, roll back the transaction. */
                $transaction->rollBack();

                /* Add flash alert with error from thrown exception. */
                Yii::$app->getSession()->addFlash('danger', $e->getMessage());
            }
        }

        return $this->redirect(['index']);
    }

    /**
     * Creates a new Tag model via Ajax request
     *
     * @return mixed
     */
    public function actionAjaxCreate()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        /* Check permissions */
        if (\Yii::$app->user->can('tagCreate')) {

            /* Create new instance */
            $model = new Tag();

            /*
             * Even though Ajax validation occurred during data entry, the call to the save method does not skip
             * validation since it is during validation that SluggableBehavior will generate a slug.
             */
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $result['notify'] = 'Tag created.';
                $result['notifyType'] = 'success';
                $result['createdId'] = $model->id;
            } else {
                $result['notify'] = implode('<br>', $model->firstErrors);
                $result['notifyType'] = 'warning';
            }
        } else {
            $result['notify'] = 'You do not have permission to create tags.';
            $result['notifyType'] = 'warning';
        }

        return $result;
    }

    /**
     * Validate data via Ajax.
     *
     * Example usage, the basic create form in modal window on page/post edit form.
     *
     * @return mixed
     */
    public function actionAjaxValidate()
    {
        $model = new Tag();

        $model->load(Yii::$app->request->post());

        Yii::$app->response->format = Response::FORMAT_JSON;

        return ActiveForm::validate($model);
    }
}

modules/backend/views/layouts/help.php
<?php

use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<?php $this->beginContent('@app/modules/admin/views/layouts/main.php'); ?>

    <div class="help-content">
        <ul>
            <li><a href="<?= Url::toRoute(['help/post']) ?>">Posts</a></li>
            <li><a href="<?= Url::toRoute(['help/image']) ?>">Images</a></li>
            <li><a href="<?= Url::toRoute(['help/tag']) ?>">Tags</a></li>
            <li><a href="<?= Url::toRoute(['help/category']) ?>">Categories</a></li>
            <li><a href="<?= Url::toRoute(['help/user']) ?>">Users</a></li>
            <li><a href="<?= Url::toRoute(['help/setting']) ?>">Settings</a></li>
        </ul>

        <div class="cell">
            <?= $content; ?>
        </div>

    </div>
<?php $this->endContent();

modules/backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */
/* @var $authenticatedUser \app\modules\base\models\User */

use app\assets\AdminAsset;
use app\modules\backend\widgets\ActionBar;
use app\modules\backend\widgets\FlashAlert;
use app\modules\base\models\Help;
use app\modules\base\models\Setting;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;

AdminAsset::register($this);

$authenticatedUser = Yii::$app->user->identity;

/* Since settings pages are all one action but separate groups, identify the group for later setting active page. */
$settingGroup = (Yii::$app->controller->id == 'setting') ? Yii::$app->getRequest()->getQueryParam('group') : null;

$bodyClass = [];
$bodyClass[] = 'color-scheme__' . Setting::getSetting('admin_color_scheme');
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title . ' - ') . Setting::getSetting('blog_title') ?> Admin</title>
    <?php $this->head() ?>
</head>
<body class="<?= implode(' ', $bodyClass) ?>">
<?php $this->beginBody() ?>

<div class="header">
    <?php
    /* This header__body is wrapped in a Pjax widget so that when pages are updated via Ajax, the changed page header
     * can be reflected to appear as it would if the page were to be refreshed. For example, when first saving a new
     * post the header changes from "New Post" to "Update Post" or when subsequent post saves are made that contain a
     * change to the post title, that changed title can be reflected in the header without requiring a page refresh.
     * The linkSelector parameter is set to false so that the links within the header will themselves not trigger Pjax.
     */
    ?>
    <?php Pjax::begin(['id' => 'header__body', 'linkSelector' => false]); ?>
    <div class="header__body">
        <div class="header__title">
            <?= $this->title ?>
        </div>
        <div class="header__breadcrumb">
            <?= Breadcrumbs::widget([
                'itemTemplate' => '<li class="header__breadcrumb-item">{link}<span class="header__breadcrumb-separator">&rsaquo;</span></li>',
                'activeItemTemplate' => '<li class="header__breadcrumb-item active">{link}</li>',
                'options' => ['class' => 'header__breadcrumb-list'],
                'homeLink' => false,
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []
            ]) ?>
        </div>
        <label class="header__sidebar-toggle" for="sidebar_main">
            <i class="fa fa-bars header__sidebar-toggle-icon" aria-hidden="true"></i>
        </label>
    </div>
    <?php Pjax::end(); ?>
</div>

<div class="main">
    <div class="sidebar sidebar_main">
        <input type="checkbox" class="sidebar__state" id="sidebar_main" />
        <div class="sidebar__content">
            <div class="sidebar__brand">
                <!--<div class="header__brand-logo">-->
                <!--<div class="logo">-->
                <!--<img src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg">-->
                <!--</div></div>-->
                <div class="sidebar__brand-name">
                    <?= Html::a(Setting::getSetting('blog_title'), Yii::$app->homeUrl, ['class' => 'sidebar__brand-link']) ?>
                    <br>
                    Admin
                </div>
            </div>
            <ul class="sidebar__list">
                <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'post') ? 'active' : null ?>">
                    <a href="<?= Url::toRoute(['post/index']) ?>" class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-book sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Posts</a>
                </li>
                <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'page') ? 'active' : null ?>">
                    <a href="<?= Url::toRoute(['page/index']) ?>" class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-file-text sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Pages</a>
                </li>
                <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'image') ? 'active' : null ?>">
                    <a href="<?= Url::toRoute(['image/index']) ?>" class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-picture-o sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Images</a>
                </li>
                <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'tag') ? 'active' : null ?>">
                    <a href="<?= Url::toRoute(['tag/index']) ?>" class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-tags sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Tags</a>
                </li>
                <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'category') ? 'active' : null ?>">
                    <a href="<?= Url::toRoute(['category/index']) ?>" class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-tag sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Categories</a>
                </li>
                <li class="sidebar__list-item sidebar__list-item_expandable <?= (in_array(Yii::$app->controller->id, ['setting', 'injection', 'user'])) ? 'sidebar__list-item_expanded' : null ?>">
                    <span class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-cogs sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Settings
                        <i class="fa fa-chevron-right sidebar__list-item-expand-indicator" aria-hidden="true"></i>
                    </span>
                    <ul class="sidebar__list sidebar__list_child">
                        <li class="sidebar__list-item <?= ($settingGroup == 'blog') ? 'active' : null ?>">
                            <a href="<?= Url::toRoute(['setting/blog']) ?>" class="sidebar__list-item-link">Blog Settings</a>
                        </li>
                        <li class="sidebar__list-item <?= ($settingGroup == 'admin') ? 'active' : null ?>">
                            <a href="<?= Url::toRoute(['setting/admin']) ?>" class="sidebar__list-item-link">Admin Settings</a>
                        </li>
                        <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'user') ? 'active' : null ?>">
                            <a href="<?= Url::toRoute(['user/index']) ?>" class="sidebar__list-item-link">Users</a>
                        </li>
                        <li class="sidebar__list-item <?= (Yii::$app->controller->id == 'injection') ? 'active' : null ?>">
                            <a href="<?= Url::toRoute(['injection/index']) ?>" class="sidebar__list-item-link">Injections</a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar__list-item sidebar__list-item_expandable <?= (Yii::$app->controller->action->id == 'profile') ? 'sidebar__list-item_expanded' : null ?>">
                    <span class="sidebar__list-item-link">
                        <i class="fa fa-fw fa-user sidebar__list-item-link-icon" aria-hidden="true"></i>
                        Account
                        <i class="fa fa-chevron-right sidebar__list-item-expand-indicator" aria-hidden="true"></i>
                    </span>
                    <ul class="sidebar__list sidebar__list_child">
                        <li class="sidebar__list-item">
                            <a href="<?= Url::toRoute(['user/view', 'id' => Yii::$app->user->id]) ?>" class="sidebar__list-item-link">Profile</a>
                        </li>
                        <li class="sidebar__list-item">
                            <a href="<?= Url::toRoute(['default/logout']) ?>" class="sidebar__list-item-link logout-link" data-method="post">Log out</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <label class="sidebar__backdrop" for="sidebar_main"></label>
    </div>

    <div class="content">
        <div class="action-bar action-bar_overflow-hidden-on-load">
            <?= ActionBar::widget() ?>
        </div>
        <?= $content ?>
    </div>
</div>

<?php Help::modal() ?>

<?= FlashAlert::widget() ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/backend/views/layouts/minimal.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AdminAsset;
use app\modules\base\models\Setting;
use app\modules\backend\widgets\FlashAlert;
use yii\helpers\Html;

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="minimal">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title . ' - ') . Setting::getSetting('blog_title') ?></title>
    <?php $this->head() ?>
</head>
<body class="color-scheme__blue-700">
<?php $this->beginBody() ?>

<div class="main">
    <div class="content content_minimal">
        <?= $content ?>
    </div>
</div>

<?= FlashAlert::widget() ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>