modules/backend/controllers/PageController.php
<?php

namespace app\modules\backend\controllers;

use app\modules\base\models\Page;
use app\modules\backend\models\PageSearch;
use yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index',
                            'view',
                            'edit',
                            'publish',
                            'unpublish',
                            'delete',
                            'generate-or-validate-slug',
                        ],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'publish' => ['POST'],
                    'unpublish' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Page models.
     * Include the most recent page or currently selected page (if provided) for preview functionality.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Page model. Only used on small screens. Larger screens show page in preview pane.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        /* Retrieve all page restore points for this primary page */
        $pageRestorePointsDataProvider = new ActiveDataProvider([
            'query' => Page::findModel($id)->pageRestorePoints(),
        ]);

        /* Return the newest restore point as the model and all page restore points */
        return $this->render('view', [
            'model' => Page::findModel($id)->newestRestorePoint(),
            'pageRestorePoints' => $pageRestorePointsDataProvider,
        ]);
    }

    /**
     * Creates a new Page model if it does not exist or updates an existing Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param null $id Primary page ID
     * @return mixed
     * @throws HttpException
     *
     */
    public function actionEdit($id = null)
    {
        /* If an ID is provided, load the modal for an update. Else, instantiate new Page for create. */
        if ($id) {
            $model = Page::findModel($id)->newestRestorePoint();
        } else {
            $model = new Page();
        }

        /* Is user authorized to create a page or update this page? */
        if ((!$id && \Yii::$app->user->can('pageCreate'))
            || ($id && \Yii::$app->user->can('pageUpdate', ['model' => $model->primaryPage()]))
        ) {

            /*
             * On this page edit page, the LinkModal displays pages/tags/categories for insertion into page content.
             * In the LinkModal, record grids are wrapped in a Pjax widget so that they may be sorted/paginated. Also
             * on this edit page, every save uses Pjax to update the header__body with an updated page title. Since
             * that those Pjax actions are accomplished via Ajax, sorting/paging through any grid inside the LinkModal
             * widget or updating the header after a save will trigger an Ajax call to this edit action. Simply checking
             * to see if this request is an Ajax request means the logic that follows will be trigger not only when the
             * form is submitted via Ajax but also when any grid in the LinkModal is sorted/paged or the header is
             * updated after a save. To prevent this, the $_GET param of "_pjax" and is also retrieved and checked. If
             * the request contains the _pjax $_GET parameter, then that particular request must be from the LinkModal
             * sorting/paging or updating of the header and the save logic below is not executed. If the _pjax $_GET
             * parameter is null, the Ajax request must be from a form submit and the save logic is executed.
             *
             * So, if this is an Ajax request that does not contain a _pjax $_GET paramter, perform the save logic.
             * Otherwise, just load the page edit form.
             */
            if (Yii::$app->request->isAjax && Yii::$app->request->get('_pjax') === null) {

                /*
                 * STEP 1: Load $_POST data into an instance of an unlocked restore point.
                 *
                 * Will either be the restore point loaded at the start of this action or one that is newly instantiated
                 * inside returnUnlockedPage().
                 */

                /*
                 * Use the existing restore point or a newly instantiated restore point, whichever is necessary to be
                 * working with and unlocked restore point. */
                $model = $model->returnUnlockedPage();

                /*
                 * Load the $_POST data into the model (will either be the existing model or the just instantiated model
                 * if the existing was locked).
                 */
                $model->load(Yii::$app->request->post());

                /*
                 * STEP 2: Save page restore point
                 *
                 * First, ensure the restore point will validate. After validation occurs, the beforeSave will fire
                 * which will create a new primary if needed (if primary_id is empty and _createPrimaryIfNull has not
                 * been changed to false). Creating the new primary takes place after validation to ensure failed
                 * validation does not result in a new primary without a child. An alternative would be to create the
                 * primary regardless then delete it if validation fails but that is just unnecessary and terrible.
                 */

                /* Contains notify and notifyType to be returned (as well as other data) to page calling the action */
                $result = null;

                /*
                 * Validate the submitted $_POST data that has been loaded into the existing restore point or a new
                 * instance.
                 */
                if (!$model->validate()) {
                    /* Page failed to validate. Return errors. */
                    $result['notify'] = implode('<br>', $model->firstErrors);
                    $result['notifyType'] = 'warning';
                } else {
                    /*
                     * Now that validation has succeeded, the page restore point can be save (which will trigger
                     * beforeSave which creates a new primary if necessary.
                     */

                    /* Save the page (either updating the existing restore point or inserting the new instance) */
                    if ($model->save()) {
                        $result['notify'] = 'Page saved.';
                        $result['notifyType'] = 'success';
                        /* Button text and enabled status for all of the action bar buttons */
                        $result['buttons'] = $model->buttons(); /* Since entire result is json, no need to json encod */
                        /* Additional result attributes */
                        $result['primary_id'] = $model->primary_id;
                        $result['action'] = Url::to(['edit', 'id' => $model->primary_id]);
                        /* Returns "first-page" */
                        $result['slug'] = $model->slug;
                        /* Returns "/2017/01/first-page" */
                        $result['url'] = Url::toRoute($model->route());
                        /* Returns "/2017/01/first-page?preview=true" */
                        $result['urlPreview'] = Url::toRoute($model->route()) . '?preview=true';
                    } else {
                        $result['notify'] = implode('<br>', $model->firstErrors);
                        $result['notifyType'] = 'warning';
                    }
                }

                /* Response will be JSON */
                Yii::$app->response->format = Response::FORMAT_JSON;

                /* Return data */
                return $result;

            } else {
                /**
                 * Before rendering the edit page, regenerate and set the slug for non-published pages.
                 * Scenario 1: Two pages were in draft status with the same slug. When Page A was published, the slug
                 * for Page B stopped being unique and cannot be used.
                 * Scenario 2: Page A was created and published. Page B was created with the same title and received a
                 * unique slug. Page A is unpublished. Page B is edited and the slug can be returned to the original
                 * value since the Page A was the reason it was changed but now Page A is no longer published.
                 */
                /* Do not automatically generate and set the slug if the page is published. */
                if ($model->status != Page::STATUS_PUBLISHED) {
                    $model->generateAndSetSlug();
                }

                /*
                 * Regardless of whether or not this restore point is currently locked, set it back to empty so that

modules/backend/views/category/_form-simple.php
<?php

use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\base\models\Category */
/* @var $formId string */
/* @var $enableAjaxValidation boolean */
/* @var $validationUrl array|string */
/* @var $action array|string */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form-simple">

    <?php $form = ActiveForm::begin([
        'id' => $formId,
        'enableAjaxValidation' => $enableAjaxValidation,
        'validationUrl' => $validationUrl,
        'action' => $action,
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= '<div class="error-summary error-summary-custom"></div>' ?>

    <?php ActiveForm::end(); ?>

</div>

modules/backend/views/category/_form.php
<?php

use yii\widgets\ActiveForm;
use app\modules\backend\widgets\ImageModal;

/* @var $this yii\web\View */
/* @var $model app\modules\base\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">

    <?php $form = ActiveForm::begin([
        'id' => 'category-form',
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'autofocus' => $model->isNewRecord]) ?>

    <?php if (!$model->isNewRecord) {
        echo $form->field($model, 'slug')->textInput(['maxlength' => true]);
    } ?>

    <?= $form->field($model, 'image', [
        'options' => ['class' => 'form-group form-group-image'],
        'template' => "{label}\n{hint}\n{error}\n{input}",
    ])->widget(\app\modules\backend\widgets\SelectImageInput::className(), [
        'sizes' => '(max-width: 543px) calc(100vw - 20px), 400px'
    ]) ?>

    <?= $form->field($model, 'description')
        ->textarea(['rows' => 3]) ?>

    <?php ActiveForm::end(); ?>

    <?= ImageModal::widget() ?>
</div>

modules/backend/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\backend\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'slug') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-scheme']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/backend/views/category/create.php
<?php

use app\modules\backend\widgets\Panel;

/* @var $this yii\web\View */
/* @var $model app\modules\base\models\Category */

$this->title = 'New Category';
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->params['action-buttons'] = [
    [
        'name' => 'main',
        'primary' => true,
        'items' => [
            [
                'icon' => 'fa-floppy-o',
                'text' => 'Save',
                'url' => null,
                'form' => 'category-form',
                'options' => null,
                'authorized' => \Yii::$app->user->can('categoryCreate'),
            ],
        ]
    ],
];
?>

<div class="category-create content-wrapper">

    <?php Panel::begin(['title' => 'Category Content']); ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

    <?php Panel::end(); ?>

</div>

modules/backend/views/category/index.php
<?php

use app\components\Functions;
use app\modules\backend\widgets\Panel;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\backend\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Categories';
$this->params['breadcrumbs'][] = $this->title;

$this->params['action-buttons'] = [
    [
        'name' => 'main',
        'primary' => true,
        'items' => [
            [
                'icon' => 'fa-plus',
                'text' => 'New Category',
                'url' => ['create'],
                'form' => null,
                'options' => null,
                'authorized' => \Yii::$app->user->can('categoryCreate'),
            ],
        ]
    ],
    /* Action bar group for record selection */
    [
        'name' => 'index-selection',
        'items' => [
            [
                'icon' => 'fa-pencil',
                'text' => 'Edit',
                'url' => null,
                'options' => [
                    'data' => [
                        'href-template' => Url::to(['update', 'id' => '0']),
                        'selection-allowed' => '1',
                    ],
                ],
                'authorized' => true,
            ],
            [
                'icon' => 'fa-trash',
                'text' => 'Delete',
                'url' => null,
                'options' => [
                    'data' => [
                        'href-template' => Url::to(['delete', 'ids' => '0']),
                        'selection-allowed' => 'N',
                    ],
                ],
                'authorized' => true,
            ],
        ]
    ]
];
?>

<div class="category-index content-wrapper">

    <?php Panel::begin(['title' => $this->title]); ?>

    <?php Pjax::begin(['id' => 'category-grid']); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'options' => ['class' => 'grid-view table-responsive table-avatar-first-column table-selectable table-selectable_avatar'],
        'emptyText' => 'No categories found. Click "New Category" above to get started.',
        'columns' => [
            [
                'format' => 'raw',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Category */
                    return Functions::getSelectableAvatar([
                        'action-bar-group' => 'index-selection',
                        'record-id' => $data->id,
                        'text' => $data->name,
                        'image' => $data->image,
                        'size' => '50px',
                    ]);
                },
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Category */
                    $result = Html::a(Html::encode($data->name), ['view', 'id' => $data->id], ['class' => 'primary']);
                    if ($data->description) {
                        $result .= Html::tag('div', $data->description, ['class' => 'secondary']);
                    } else {
                        $result .= Html::tag('div', 'No description', ['class' => 'secondary secondary-accent']);
                    }
                    return $result;
                },
            ],
            'slug',
            'primary_posts_count',
            'primary_pages_count',
        ],
    ]); ?>

    <?php Pjax::end(); ?>

    <?php Panel::end(); ?>

</div>

modules/backend/views/category/update.php
<?php

use app\modules\backend\widgets\Panel;
use yii\helpers\StringHelper;

/* @var $this yii\web\View */
/* @var $model app\modules\base\models\Category */

$title = $model->name;
$truncatedTitle = StringHelper::truncate($title, 20);

$this->title = 'Update Category: ' . $title;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $truncatedTitle, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';

$this->params['action-buttons'] = [
    [
        'name' => 'main',
        'primary' => true,
        'items' => [
            [
                'icon' => 'fa-floppy-o',
                'text' => 'Save',
                'url' => null,
                'form' => 'category-form',
                'options' => null,
                'authorized' => \Yii::$app->user->can('categoryUpdate', ['model' => $model]),
            ],
        ]
    ],
];
?>

<div class="category-update content-wrapper">

    <?php Panel::begin(['title' => 'Category Content']); ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

    <?php Panel::end(); ?>

</div>

modules/backend/views/category/view.php
<?php

use app\modules\backend\widgets\Panel;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\modules\base\models\Category */
/* @var $posts yii\data\ActiveDataProvider */
/* @var $pages yii\data\ActiveDataProvider */

$title = $model->name;

$this->title = 'View Category: ' . $title;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $title;

$this->params['action-buttons'] = [
    [
        'name' => 'main',
        'primary' => true,
        'items' => [
            [
                'icon' => 'fa-pencil',
                'text' => 'Edit',
                'url' => ['update', 'id' => $model->id],
                'options' => null,
                'authorized' => \Yii::$app->user->can('categoryUpdate', ['model' => $model]),
            ],
            [
                'icon' => 'fa-trash',
                'text' => 'Delete',
                'url' => ['delete', 'ids' => $model->id],
                'options' => [
                    'data' => ['confirm' => 'Are you sure you want to delete this category?']
                ],
                'authorized' => \Yii::$app->user->can('categoryDelete', ['model' => $model]),
            ],
        ]
    ],
];
?>

<div class="category-view content-wrapper">

    <?php Panel::begin(['title' => 'Category Information']); ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'slug',
            'image',
            'description',
            'primary_posts_count',
            'primary_pages_count',
        ],
    ]) ?>

    <?php Panel::end(); ?>

    <?php Panel::begin(['title' => 'Category Posts', 'collapsable' => true, 'collapsed' => true]); ?>

    <?php Pjax::begin(['id' => 'post-subgrid', 'enablePushState' => false, 'linkSelector' => 'thead a, .pagination a']); ?>

    <?= GridView::widget([
        'dataProvider' => $posts,
        'options' => ['class' => 'grid-view table-responsive'],
        'tableOptions' => ['class' => 'table table-expanded'],
        'columns' => [
            [
                'attribute' => 'title_revised',
                'label' => 'Title',
                'format' => 'raw',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Post */
                    return Html::a(Html::encode($data->title_revised), ['post/view', 'id' => $data->id]);
                },
            ],
            [
                'attribute' => 'status',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Post */
                    return $data->statusText();
                },
                'contentOptions' => function ($model) {
                    /* @var $model app\modules\base\models\Post */
                    return ['class' => 'post-meta ' . strtolower($model->statusText())];
                }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

    <?php Panel::end(); ?>

    <?php Panel::begin(['title' => 'Category Pages', 'collapsable' => true, 'collapsed' => true]); ?>

    <?php Pjax::begin(['id' => 'page-subgrid', 'enablePushState' => false, 'linkSelector' => 'thead a, .pagination a']); ?>

    <?= GridView::widget([
        'dataProvider' => $pages,
        'options' => ['class' => 'grid-view table-responsive'],
        'tableOptions' => ['class' => 'table table-expanded'],
        'columns' => [
            [
                'attribute' => 'title_revised',
                'label' => 'Title',
                'format' => 'raw',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Page */
                    return Html::a(Html::encode($data->title_revised), ['page/view', 'id' => $data->id]);
                },
            ],
            [
                'attribute' => 'status',
                'value' => function ($data) {
                    /* @var $data app\modules\base\models\Page */
                    return $data->statusText();
                },
                'contentOptions' => function ($model) {
                    /* @var $model app\modules\base\models\Page */
                    return ['class' => 'page-meta ' . strtolower($model->statusText())];
                }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

    <?php Panel::end(); ?>

</div>